### PR TITLE
Add Nello796 to contributor list

### PR DESCRIPTION
**Pull request by Nello796**
I've pushed everything with another branch because I had some problems with the old ones.

### CODE REVIEW

**Review by KatonaCsaba — COMMENTED** [review]
More than perfect :D

**Comment by Nello796** [comment]
> More than perfect :D

Good!  you should just accept it 🤓

**Review by mayramsay — APPROVED** [review]
Very good, Nello!

**Comment by zsoltime** [comment]
Anyone wants to merge this PR? Don't be shy :)

**Pull request merged**
